### ISSUE TITLE
About training data sets

### ISSUE THREAD

**Issue by sunskys** [Wendy0601/Mobile-Eye-Gaze-Estimation-with-Deep-Learning#1]
Hello, I was studying gazing recently and I am happy to see your project. I want to reproduce your project locally, I would like to consult: How your data set is obtained, is a public data set produced? Is it possible to give an example, thank you!

**Comment by Wendy0601** [comment]
no, it is a not a public dataset but is given in a class.

I do not know the details.

I will try to update this project with examples.

thank you for your suggestion

Best regards,

Wenting Li

Department of Electrical, Computer & Systems Engineering
Rensselaer Polytechnic Institute, Troy, NY 12180

2018-01-01 21:07 GMT-05:00 sunskys <notifications@github.com>:

**Comment by sunskys** [comment]
Thank you for your reply in the night. Can you share the relevant data set? I only use as academic research, I will indicate the copyright information in the course of use, thank you!

**Comment by Wendy0601** [comment]
The dataset is too large to upload, please tell me your email and I can send it to you.

**Comment by sunskys** [comment]
690510604@qq.com，thank you

**Comment by lucaskyle** [comment]
dear Wendy0601:
could u send me a copy of datasets? im also reproducing ur project.   
lucasspecialk@hotmail.com
